GSA_HEADERS = [
    "Base Product or Accessory",
    "Manufacturer",
    "Manufacturer Part Number",
    "Vendor Part Number",
    "Special Item Number",
    "Item Name",
    "Item Description",
    "Recycled Content Percent",
    "Unit of Measure",
    "Quantity Per Pack",
    "Quantity Unit UOM",
    "Commercial Price",
    "Most Favored Customer Name",
    "Most Favored Customer Price",
    "Govt Price (No Fee)",
    "Govt Price (With Fee)",
    "Country of Origin",
    "Delivery Days",
    "Lead Time Code",
    "FOB US",
    "FOB AK",
    "FOB HI",
    "FOB PR",
    "National Stock Number",
    "UPC",
    "UNSPSC",
    "Sale Price With Fee",
    "Start Date",
    "Stop Date",
    "Default Photo",
    "Photo 2",
    "Photo 3",
    "Photo 4",
    "Product URL",
    "Warranty Period",
    "Warranty Unit Of Time",
    "Length",
    "Width",
    "Height",
    "Physical UOM",
    "Weight Lbs",
    "Product Info Code",
    "508 URL",
    "Hazmat",
    "Dealer Cost",
    "MFC Markup %",
    "Govt Markup %",
]
