"""model changed in modifications, jobs

Revision ID: 03d1859734a6
Revises: 5015dbe2e8cd
Create Date: 2026-02-06 15:23:40.667384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d1859734a6'
down_revision: Union[str, Sequence[str], None] = '5015dbe2e8cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_profiles', sa.Column('company_logo', sa.String(length=250), nullable=True), schema='dev')
    op.alter_column('client_profiles', 'company_name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=51),
               existing_nullable=False,
               schema='dev')
    op.add_column('modification_action', sa.Column('old_name', sa.Text(), nullable=True), schema='dev')
    op.add_column('modification_action', sa.Column('new_name', sa.Text(), nullable=True), schema='dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modification_action', 'new_name', schema='dev')
    op.drop_column('modification_action', 'old_name', schema='dev')
    op.alter_column('client_profiles', 'company_name',
               existing_type=sa.String(length=51),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               schema='dev')
    op.drop_column('client_profiles', 'company_logo', schema='dev')
    # ### end Alembic commands ###
