"""Company logo

Revision ID: 1e2c78a387aa
Revises: 8d0289a30017
Create Date: 2026-02-24 11:08:08.722312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e2c78a387aa'
down_revision: Union[str, Sequence[str], None] = '8d0289a30017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_profiles', sa.Column('company_logo_url', sa.String(length=350), nullable=True), schema='dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_profiles', 'company_logo_url', schema='dev')
    # ### end Alembic commands ###
