"""add is_tdr to client_contracts

Revision ID: 622fea50f4d1
Revises: eaa767504c1d
Create Date: 2026-03-13 17:40:22.307496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622fea50f4d1'
down_revision: Union[str, Sequence[str], None] = 'eaa767504c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_contracts', sa.Column('is_tdr', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_contracts', 'is_tdr', schema='dev')
    # ### end Alembic commands ###
