"""updated columns tdr and expedited delivery

Revision ID: 67360b96260b
Revises: 148afca7187e
Create Date: 2026-04-13 12:20:47.381206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67360b96260b'
down_revision: Union[str, Sequence[str], None] = '148afca7187e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_contracts', 'expedited_delivery_time',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True,
               schema='dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_contracts', 'expedited_delivery_time',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True,
               schema='dev')
    # ### end Alembic commands ###
