"""fix negotiators

Revision ID: 717ec4c03a01
Revises: bcd85fe26cab
Create Date: 2026-03-20 22:41:52.166485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '717ec4c03a01'
down_revision: Union[str, Sequence[str], None] = 'bcd85fe26cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negotiators',
    sa.Column('negotiator_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone_no', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip', sa.String(length=7), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['dev.client_profiles.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('negotiator_id'),
    schema='dev'
    )
    op.add_column('client_contracts', sa.Column('epa_method_mechanism', sa.String(length=255), nullable=True), schema='dev')
    op.add_column('client_contracts', sa.Column('is_hazardous', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='dev')
    op.add_column('client_contracts', sa.Column('is_tdr', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='dev')
    op.alter_column('client_contracts', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='dev')
    op.add_column('client_profiles', sa.Column('company_logo_url', sa.String(length=350), nullable=True), schema='dev')
    op.alter_column('client_profiles', 'company_name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=51),
               existing_nullable=False,
               schema='dev')
    op.drop_constraint(op.f('client_profiles_company_email_key'), 'client_profiles', schema='dev', type_='unique')
    op.drop_constraint(op.f('client_profiles_company_phone_no_key'), 'client_profiles', schema='dev', type_='unique')
    op.drop_constraint(op.f('client_profiles_contact_officer_email_key'), 'client_profiles', schema='dev', type_='unique')
    op.drop_constraint(op.f('client_profiles_contact_officer_phone_no_key'), 'client_profiles', schema='dev', type_='unique')
    op.drop_column('client_profiles', 'contact_officer_address', schema='dev')
    op.drop_column('client_profiles', 'contact_officer_phone_no', schema='dev')
    op.drop_column('client_profiles', 'contact_officer_name', schema='dev')
    op.drop_column('client_profiles', 'contact_officer_state', schema='dev')
    op.drop_column('client_profiles', 'contact_officer_city', schema='dev')
    op.drop_column('client_profiles', 'contact_officer_email', schema='dev')
    op.drop_column('client_profiles', 'contact_officer_zip', schema='dev')
    op.alter_column('cpl_list', 'manufacturer_name',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='dev')
    op.alter_column('cpl_list', 'item_name',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='dev')
    op.add_column('file_uploads', sa.Column('job_id', sa.Integer(), nullable=True), schema='dev')
    op.create_foreign_key(None, 'file_uploads', 'jobs', ['job_id'], ['job_id'], source_schema='dev', referent_schema='dev', ondelete='SET NULL')
    op.add_column('modification_action', sa.Column('old_name', sa.Text(), nullable=True), schema='dev')
    op.add_column('modification_action', sa.Column('new_name', sa.Text(), nullable=True), schema='dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modification_action', 'new_name', schema='dev')
    op.drop_column('modification_action', 'old_name', schema='dev')
    op.drop_constraint(None, 'file_uploads', schema='dev', type_='foreignkey')
    op.drop_column('file_uploads', 'job_id', schema='dev')
    op.alter_column('cpl_list', 'item_name',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='dev')
    op.alter_column('cpl_list', 'manufacturer_name',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='dev')
    op.add_column('client_profiles', sa.Column('contact_officer_zip', sa.VARCHAR(length=7), autoincrement=False, nullable=True), schema='dev')
    op.add_column('client_profiles', sa.Column('contact_officer_email', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='dev')
    op.add_column('client_profiles', sa.Column('contact_officer_city', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='dev')
    op.add_column('client_profiles', sa.Column('contact_officer_state', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='dev')
    op.add_column('client_profiles', sa.Column('contact_officer_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True), schema='dev')
    op.add_column('client_profiles', sa.Column('contact_officer_phone_no', sa.VARCHAR(length=15), autoincrement=False, nullable=True), schema='dev')
    op.add_column('client_profiles', sa.Column('contact_officer_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='dev')
    op.create_unique_constraint(op.f('client_profiles_contact_officer_phone_no_key'), 'client_profiles', ['contact_officer_phone_no'], schema='dev', postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('client_profiles_contact_officer_email_key'), 'client_profiles', ['contact_officer_email'], schema='dev', postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('client_profiles_company_phone_no_key'), 'client_profiles', ['company_phone_no'], schema='dev', postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('client_profiles_company_email_key'), 'client_profiles', ['company_email'], schema='dev', postgresql_nulls_not_distinct=False)
    op.alter_column('client_profiles', 'company_name',
               existing_type=sa.String(length=51),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               schema='dev')
    op.drop_column('client_profiles', 'company_logo_url', schema='dev')
    op.alter_column('client_contracts', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='dev')
    op.drop_column('client_contracts', 'is_tdr', schema='dev')
    op.drop_column('client_contracts', 'is_hazardous', schema='dev')
    op.drop_column('client_contracts', 'epa_method_mechanism', schema='dev')
    op.drop_table('negotiators', schema='dev')
    # ### end Alembic commands ###
