"""Changed the client profile

Revision ID: 8d0289a30017
Revises: 03d1859734a6
Create Date: 2026-02-13 12:02:46.252790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0289a30017'
down_revision: Union[str, Sequence[str], None] = '03d1859734a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_contracts', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='dev')
    op.drop_column('client_profiles', 'company_logo', schema='dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_profiles', sa.Column('company_logo', sa.VARCHAR(), autoincrement=False, nullable=True), schema='dev')
    op.alter_column('client_contracts', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='dev')
    # ### end Alembic commands ###
