"""add job_id to file_uploads

Revision ID: bcd85fe26cab
Revises: 1e2c78a387aa
Create Date: 2026-03-12 17:43:02.037396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd85fe26cab'
down_revision: Union[str, Sequence[str], None] = '1e2c78a387aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_uploads', sa.Column('job_id', sa.Integer(), nullable=True), schema='dev')
    op.create_foreign_key(None, 'file_uploads', 'jobs', ['job_id'], ['job_id'], source_schema='dev', referent_schema='dev', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file_uploads', schema='dev', type_='foreignkey')
    op.drop_column('file_uploads', 'job_id', schema='dev')
    # ### end Alembic commands ###
