"""empty message

Revision ID: bea9f1b6a224
Revises: 
Create Date: 2026-02-05 11:37:26.332802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bea9f1b6a224'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs', schema='dev')
    op.drop_table('template_documents', schema='dev')
    op.drop_table('file_uploads', schema='dev')
    op.drop_index(op.f('ix_product_master_client'), table_name='product_master', schema='dev')
    op.drop_index(op.f('ix_product_master_signature'), table_name='product_master', schema='dev')
    op.drop_index(op.f('ux_product_master_identity'), table_name='product_master', schema='dev')
    op.drop_table('product_master', schema='dev')
    op.drop_table('client_contracts', schema='dev')
    op.drop_table('alembic_version')
    op.drop_table('product_dim', schema='dev')
    op.drop_table('modification_action', schema='dev')
    op.drop_table('cpl_list', schema='dev')
    op.drop_index(op.f('ix_product_history_client'), table_name='product_history', schema='dev')
    op.drop_index(op.f('ix_product_history_current'), table_name='product_history', schema='dev')
    op.drop_index(op.f('ix_product_history_product_time'), table_name='product_history', schema='dev')
    op.drop_index(op.f('ix_product_history_signature'), table_name='product_history', schema='dev')
    op.drop_table('product_history', schema='dev')
    op.drop_table('role', schema='dev')
    op.drop_table('client_profiles', schema='dev')
    op.drop_table('status', schema='dev')
    op.drop_table('users', schema='dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('phone_no', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('cognito_sub', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['dev.role.role_id'], name=op.f('users_role_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('users_pkey')),
    sa.UniqueConstraint('cognito_sub', name=op.f('users_cognito_sub_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('phone_no', name=op.f('users_phone_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='dev'
    )
    op.create_table('status',
    sa.Column('status_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('status_id', name=op.f('status_pkey')),
    schema='dev'
    )
    op.create_table('client_profiles',
    sa.Column('client_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=51), autoincrement=False, nullable=False),
    sa.Column('company_email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('company_phone_no', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('company_address', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('company_city', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('company_state', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('company_zip', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('contact_officer_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('contact_officer_email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('contact_officer_phone_no', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('contact_officer_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('contact_officer_city', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('contact_officer_state', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('contact_officer_zip', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['dev.status.status_id'], name=op.f('client_profiles_status_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id', name=op.f('client_profiles_pkey')),
    sa.UniqueConstraint('company_email', name=op.f('client_profiles_company_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('company_phone_no', name=op.f('client_profiles_company_phone_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('contact_officer_email', name=op.f('client_profiles_contact_officer_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('contact_officer_phone_no', name=op.f('client_profiles_contact_officer_phone_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='dev'
    )
    op.create_table('role',
    sa.Column('role_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('role_id', name=op.f('role_pkey')),
    schema='dev'
    )
    op.create_table('product_history',
    sa.Column('product_history_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('manufacturer_part_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('vendor_part_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sin', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('item_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('item_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recycled_content_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('uom', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('quantity_per_pack', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity_unit_uom', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('commercial_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('mfc_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('mfc_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('govt_price_no_fee', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('govt_price_with_fee', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('country_of_origin', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('delivery_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lead_time_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('fob_us', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('fob_ak', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('fob_hi', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('fob_pr', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('nsn', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('upc', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('unspsc', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sale_price_with_fee', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('stop_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('default_photo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('photo_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('photo_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('photo_4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('warranty_period', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('warranty_unit_of_time', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('length', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('width', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('height', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('physical_uom', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('weight_lbs', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('product_info_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('url_508', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hazmat', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('dealer_cost', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('mfc_markup_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('govt_markup_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('row_signature', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('effective_start_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('effective_end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_current', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['dev.client_profiles.client_id'], name=op.f('product_history_client_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['dev.product_master.product_id'], name=op.f('product_history_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_history_id', name=op.f('product_history_pkey')),
    schema='dev'
    )
    op.create_index(op.f('ix_product_history_signature'), 'product_history', ['product_id', 'row_signature'], unique=False, schema='dev')
    op.create_index(op.f('ix_product_history_product_time'), 'product_history', ['product_id', 'effective_start_date'], unique=False, schema='dev')
    op.create_index(op.f('ix_product_history_current'), 'product_history', ['product_id', 'is_current'], unique=False, schema='dev')
    op.create_index(op.f('ix_product_history_client'), 'product_history', ['client_id'], unique=False, schema='dev')
    op.create_table('cpl_list',
    sa.Column('cpl_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('manufacturer_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('manufacturer_part_number', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('item_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('commercial_list_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('origin_country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['dev.client_profiles.client_id'], name=op.f('cpl_list_client_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['dev.users.user_id'], name=op.f('cpl_list_uploaded_by_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('cpl_id', name=op.f('cpl_list_pkey')),
    schema='dev'
    )
    op.create_table('modification_action',
    sa.Column('action_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cpl_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('old_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('new_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('old_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('new_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('old_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('new_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('number_of_items_impacted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['dev.client_profiles.client_id'], name=op.f('modification_action_client_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cpl_id'], ['dev.cpl_list.cpl_id'], name=op.f('modification_action_cpl_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['dev.jobs.job_id'], name=op.f('modification_action_job_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['dev.product_master.product_id'], name=op.f('modification_action_product_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['dev.users.user_id'], name=op.f('modification_action_user_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('action_id', name=op.f('modification_action_pkey')),
    schema='dev'
    )
    op.create_table('product_dim',
    sa.Column('dim_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('length', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('width', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('height', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('physical_uom', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('weight_lbs', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('warranty_period', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('photo_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('photo_path', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['dev.product_master.product_id'], name=op.f('product_dim_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dim_id', name=op.f('product_dim_pkey')),
    schema='dev'
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pk'))
    )
    op.create_table('client_contracts',
    sa.Column('client_profile_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contract_officer_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('contract_officer_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('contract_officer_city', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('contract_officer_state', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('contract_officer_zip', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('contract_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('origin_country', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('gsa_proposed_discount', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('q_v_discount', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('additional_concessions', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('normal_delivery_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expedited_delivery_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fob_term', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('energy_star_compliance', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_company_logo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('signatory_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('signatory_title', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['dev.client_profiles.client_id'], name=op.f('client_contracts_client_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_profile_id', name=op.f('client_contracts_pkey')),
    sa.UniqueConstraint('client_id', name=op.f('client_contracts_client_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='dev'
    )
    op.create_table('product_master',
    sa.Column('product_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('manufacturer_part_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('vendor_part_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sin', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('item_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('item_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recycled_content_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('uom', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('quantity_per_pack', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity_unit_uom', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('commercial_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('mfc_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('mfc_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('govt_price_no_fee', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('govt_price_with_fee', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('country_of_origin', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('delivery_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lead_time_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('fob_us', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('fob_ak', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('fob_hi', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('fob_pr', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('nsn', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('upc', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('unspsc', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sale_price_with_fee', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('stop_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('default_photo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('photo_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('photo_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('photo_4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('warranty_period', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('warranty_unit_of_time', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('length', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('width', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('height', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('physical_uom', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('weight_lbs', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('product_info_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('url_508', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hazmat', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('dealer_cost', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('mfc_markup_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('govt_markup_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('row_signature', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['dev.client_profiles.client_id'], name=op.f('product_master_client_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('product_id', name=op.f('product_master_pkey')),
    schema='dev'
    )
    op.create_index(op.f('ux_product_master_identity'), 'product_master', ['client_id', 'manufacturer', 'manufacturer_part_number'], unique=True, schema='dev')
    op.create_index(op.f('ix_product_master_signature'), 'product_master', ['row_signature'], unique=False, schema='dev')
    op.create_index(op.f('ix_product_master_client'), 'product_master', ['client_id'], unique=False, schema='dev')
    op.create_table('file_uploads',
    sa.Column('upload_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('s3_saved_filename', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('s3_saved_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['dev.client_profiles.client_id'], name=op.f('file_uploads_client_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['dev.users.user_id'], name=op.f('file_uploads_uploaded_by_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['dev.users.user_id'], name=op.f('file_uploads_user_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('upload_id', name=op.f('file_uploads_pkey')),
    schema='dev'
    )
    op.create_table('template_documents',
    sa.Column('template_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('template_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_s3_location', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('template_id', name=op.f('template_documents_pkey')),
    schema='dev'
    )
    op.create_table('jobs',
    sa.Column('job_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['dev.client_profiles.client_id'], name=op.f('jobs_client_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_id'], ['dev.status.status_id'], name=op.f('jobs_status_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['dev.users.user_id'], name=op.f('jobs_user_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('job_id', name=op.f('jobs_pkey')),
    schema='dev'
    )
    # ### end Alembic commands ###
