"""empty message

Revision ID: c76b3590c375
Revises: 
Create Date: 2026-01-20 19:26:09.928228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c76b3590c375'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=10), nullable=False),
    sa.Column('created_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_role_role_id'), 'role', ['role_id'], unique=False)
    op.create_table('status',
    sa.Column('status_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_code', sa.String(length=10), nullable=False),
    sa.Column('created_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_index(op.f('ix_status_status_id'), 'status', ['status_id'], unique=False)
    op.create_table('template_documents',
    sa.Column('template_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.Text(), nullable=False),
    sa.Column('file_s3_location', sa.Text(), nullable=False),
    sa.Column('created_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_index(op.f('ix_template_documents_template_id'), 'template_documents', ['template_id'], unique=False)
    op.create_table('client_profiles',
    sa.Column('client_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=30), nullable=False),
    sa.Column('company_email', sa.String(length=50), nullable=False),
    sa.Column('company_phone_no', sa.String(length=15), nullable=False),
    sa.Column('company_address', sa.String(length=50), nullable=False),
    sa.Column('company_city', sa.String(length=50), nullable=False),
    sa.Column('company_state', sa.String(length=50), nullable=False),
    sa.Column('company_zip', sa.String(length=7), nullable=False),
    sa.Column('contact_officer_name', sa.String(length=30), nullable=True),
    sa.Column('contact_officer_email', sa.String(length=50), nullable=True),
    sa.Column('contact_officer_phone_no', sa.String(length=15), nullable=True),
    sa.Column('contact_officer_address', sa.String(length=50), nullable=True),
    sa.Column('contact_officer_city', sa.String(length=50), nullable=True),
    sa.Column('contact_officer_state', sa.String(length=50), nullable=True),
    sa.Column('contact_officer_zip', sa.String(length=7), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['status'], ['status.status_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('company_email'),
    sa.UniqueConstraint('company_phone_no'),
    sa.UniqueConstraint('contact_officer_email'),
    sa.UniqueConstraint('contact_officer_phone_no')
    )
    op.create_index(op.f('ix_client_profiles_client_id'), 'client_profiles', ['client_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone_no', sa.String(length=15), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cognito_sub', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('cognito_sub'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_no')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('client_contracts',
    sa.Column('client_profile_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_officer_name', sa.String(length=30), nullable=True),
    sa.Column('contract_officer_address', sa.String(length=50), nullable=True),
    sa.Column('contract_officer_city', sa.String(length=50), nullable=True),
    sa.Column('contract_officer_state', sa.String(length=50), nullable=True),
    sa.Column('contract_officer_zip', sa.String(length=7), nullable=True),
    sa.Column('contract_number', sa.String(length=50), nullable=False),
    sa.Column('origin_country', sa.String(length=50), nullable=True),
    sa.Column('gsa_proposed_discount', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('q_v_discount', sa.String(length=50), nullable=True),
    sa.Column('additional_concessions', sa.String(length=50), nullable=True),
    sa.Column('normal_delivery_time', sa.Integer(), nullable=True),
    sa.Column('expedited_delivery_time', sa.Integer(), nullable=True),
    sa.Column('fob_term', sa.String(length=50), nullable=True),
    sa.Column('energy_star_compliance', sa.String(length=50), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_company_logo', sa.String(length=50), nullable=True),
    sa.Column('signatory_name', sa.String(length=128), nullable=True),
    sa.Column('signatory_title', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_profile_id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index(op.f('ix_client_contracts_client_profile_id'), 'client_contracts', ['client_profile_id'], unique=False)
    op.create_table('cpl_list',
    sa.Column('cpl_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_name', sa.Text(), nullable=False),
    sa.Column('manufacturer_part_number', sa.Text(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=False),
    sa.Column('item_description', sa.Text(), nullable=True),
    sa.Column('commercial_list_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('origin_country', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('cpl_id')
    )
    op.create_index(op.f('ix_cpl_list_cpl_id'), 'cpl_list', ['cpl_id'], unique=False)
    op.create_table('file_uploads',
    sa.Column('upload_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('s3_saved_filename', sa.Text(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('s3_saved_path', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.create_index(op.f('ix_file_uploads_upload_id'), 'file_uploads', ['upload_id'], unique=False)
    op.create_table('jobs',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status'], ['status.status_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=False)
    op.create_table('product_master',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=50), nullable=False),
    sa.Column('item_description', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.String(length=50), nullable=False),
    sa.Column('manufacturer_part_number', sa.String(length=50), nullable=False),
    sa.Column('client_part_number', sa.String(length=50), nullable=True),
    sa.Column('sin', sa.String(length=50), nullable=True),
    sa.Column('commercial_list_price', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('country_of_origin', sa.String(length=50), nullable=True),
    sa.Column('recycled_content_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('uom', sa.String(length=50), nullable=True),
    sa.Column('quantity_per_pack', sa.Integer(), nullable=True),
    sa.Column('quantity_unit_uom', sa.String(length=50), nullable=True),
    sa.Column('nsn', sa.String(length=50), nullable=True),
    sa.Column('upc', sa.String(length=50), nullable=True),
    sa.Column('unspsc', sa.String(length=50), nullable=True),
    sa.Column('hazmat', sa.String(length=50), nullable=True),
    sa.Column('product_info_code', sa.String(length=50), nullable=True),
    sa.Column('url_508', sa.Text(), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('row_signature', sa.String(length=64), nullable=False),
    sa.Column('created_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index('ix_product_master_client', 'product_master', ['client_id'], unique=False)
    op.create_index('ix_product_master_product_id', 'product_master', ['product_id'], unique=False)
    op.create_index('ix_product_master_signature', 'product_master', ['row_signature'], unique=False)
    op.create_index('ux_product_master_identity', 'product_master', ['client_id', 'manufacturer', 'manufacturer_part_number'], unique=True)
    op.create_table('modification_action',
    sa.Column('action_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('old_description', sa.Text(), nullable=True),
    sa.Column('new_description', sa.Text(), nullable=True),
    sa.Column('number_of_items_impacted', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index(op.f('ix_modification_action_action_id'), 'modification_action', ['action_id'], unique=False)
    op.create_table('product_dim',
    sa.Column('dim_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('width', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('height', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('physical_uom', sa.String(length=50), nullable=True),
    sa.Column('weight_lbs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('warranty_period', sa.Integer(), nullable=True),
    sa.Column('photo_type', sa.String(length=50), nullable=True),
    sa.Column('photo_path', sa.String(length=50), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product_master.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dim_id')
    )
    op.create_index(op.f('ix_product_dim_dim_id'), 'product_dim', ['dim_id'], unique=False)
    op.create_table('product_history',
    sa.Column('product_history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=50), nullable=False),
    sa.Column('item_description', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.String(length=50), nullable=False),
    sa.Column('manufacturer_part_number', sa.String(length=50), nullable=False),
    sa.Column('client_part_number', sa.String(length=50), nullable=True),
    sa.Column('sin', sa.String(length=50), nullable=True),
    sa.Column('country_of_origin', sa.String(length=50), nullable=True),
    sa.Column('recycled_content_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('uom', sa.String(length=50), nullable=True),
    sa.Column('quantity_per_pack', sa.Integer(), nullable=True),
    sa.Column('quantity_unit_uom', sa.String(length=50), nullable=True),
    sa.Column('nsn', sa.String(length=50), nullable=True),
    sa.Column('upc', sa.String(length=50), nullable=True),
    sa.Column('unspsc', sa.String(length=50), nullable=True),
    sa.Column('hazmat', sa.String(length=50), nullable=True),
    sa.Column('product_info_code', sa.String(length=50), nullable=True),
    sa.Column('url_508', sa.Text(), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('row_signature', sa.String(length=64), nullable=False),
    sa.Column('effective_start_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('effective_end_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['product_master.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_history_id')
    )
    op.create_index('ix_product_history_client', 'product_history', ['client_id'], unique=False)
    op.create_index('ix_product_history_current', 'product_history', ['product_id', 'is_current'], unique=False)
    op.create_index(op.f('ix_product_history_product_history_id'), 'product_history', ['product_history_id'], unique=False)
    op.create_index('ix_product_history_product_time', 'product_history', ['product_id', 'effective_start_date'], unique=False)
    op.create_index('ix_product_history_signature', 'product_history', ['product_id', 'row_signature'], unique=False)
    op.drop_index(op.f('ix_toys_id'), table_name='toys')
    op.drop_index(op.f('ix_toys_name'), table_name='toys')
    op.drop_table('toys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('toys_pkey'))
    )
    op.create_index(op.f('ix_toys_name'), 'toys', ['name'], unique=False)
    op.create_index(op.f('ix_toys_id'), 'toys', ['id'], unique=False)
    op.drop_index('ix_product_history_signature', table_name='product_history')
    op.drop_index('ix_product_history_product_time', table_name='product_history')
    op.drop_index(op.f('ix_product_history_product_history_id'), table_name='product_history')
    op.drop_index('ix_product_history_current', table_name='product_history')
    op.drop_index('ix_product_history_client', table_name='product_history')
    op.drop_table('product_history')
    op.drop_index(op.f('ix_product_dim_dim_id'), table_name='product_dim')
    op.drop_table('product_dim')
    op.drop_index(op.f('ix_modification_action_action_id'), table_name='modification_action')
    op.drop_table('modification_action')
    op.drop_index('ux_product_master_identity', table_name='product_master')
    op.drop_index('ix_product_master_signature', table_name='product_master')
    op.drop_index('ix_product_master_product_id', table_name='product_master')
    op.drop_index('ix_product_master_client', table_name='product_master')
    op.drop_table('product_master')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_file_uploads_upload_id'), table_name='file_uploads')
    op.drop_table('file_uploads')
    op.drop_index(op.f('ix_cpl_list_cpl_id'), table_name='cpl_list')
    op.drop_table('cpl_list')
    op.drop_index(op.f('ix_client_contracts_client_profile_id'), table_name='client_contracts')
    op.drop_table('client_contracts')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_client_profiles_client_id'), table_name='client_profiles')
    op.drop_table('client_profiles')
    op.drop_index(op.f('ix_template_documents_template_id'), table_name='template_documents')
    op.drop_table('template_documents')
    op.drop_index(op.f('ix_status_status_id'), table_name='status')
    op.drop_table('status')
    op.drop_index(op.f('ix_role_role_id'), table_name='role')
    op.drop_table('role')
    # ### end Alembic commands ###
