"""migrate_negotiators_and_contract_fields

Revision ID: eaa767504c1d
Revises: bcd85fe26cab
Create Date: 2026-03-13 12:12:00.982705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa767504c1d'
down_revision: Union[str, Sequence[str], None] = 'bcd85fe26cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_contracts', sa.Column('epa_method_mechanism', sa.String(length=255), nullable=True), schema='dev')
    op.add_column('client_contracts', sa.Column('is_hazardous', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='dev')
    op.drop_constraint(op.f('client_profiles_contact_officer_email_key'), 'client_profiles', schema='dev', type_='unique')
    op.drop_constraint(op.f('client_profiles_contact_officer_phone_no_key'), 'client_profiles', schema='dev', type_='unique')
    op.drop_column('client_profiles', 'contact_officer_state', schema='dev')
    op.drop_column('client_profiles', 'contact_officer_zip', schema='dev')
    op.drop_column('client_profiles', 'contact_officer_name', schema='dev')
    op.drop_column('client_profiles', 'contact_officer_phone_no', schema='dev')
    op.drop_column('client_profiles', 'contact_officer_email', schema='dev')
    op.drop_column('client_profiles', 'contact_officer_address', schema='dev')
    op.drop_column('client_profiles', 'contact_officer_city', schema='dev')
    op.alter_column('negotiators', 'zip',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=7),
               existing_nullable=True,
               schema='dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('negotiators', 'zip',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               schema='dev')
    op.add_column('client_profiles', sa.Column('contact_officer_city', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='dev')
    op.add_column('client_profiles', sa.Column('contact_officer_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='dev')
    op.add_column('client_profiles', sa.Column('contact_officer_email', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='dev')
    op.add_column('client_profiles', sa.Column('contact_officer_phone_no', sa.VARCHAR(length=15), autoincrement=False, nullable=True), schema='dev')
    op.add_column('client_profiles', sa.Column('contact_officer_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True), schema='dev')
    op.add_column('client_profiles', sa.Column('contact_officer_zip', sa.VARCHAR(length=7), autoincrement=False, nullable=True), schema='dev')
    op.add_column('client_profiles', sa.Column('contact_officer_state', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='dev')
    op.create_unique_constraint(op.f('client_profiles_contact_officer_phone_no_key'), 'client_profiles', ['contact_officer_phone_no'], schema='dev', postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('client_profiles_contact_officer_email_key'), 'client_profiles', ['contact_officer_email'], schema='dev', postgresql_nulls_not_distinct=False)
    op.drop_column('client_contracts', 'is_hazardous', schema='dev')
    op.drop_column('client_contracts', 'epa_method_mechanism', schema='dev')
    # ### end Alembic commands ###
